### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by ghost** [techchrism/insomnia-plugin-valorant#2]
OS: macOS Monterey 12.1
Insomnia Version: 2021.7.2
Node Version: 17.1.0

Failed to load plugin insomnia-plugin-valorant
Stack Trace: 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at Object.<anonymous> (/Users/ahlw/Library/Application Support/Insomnia/plugins/insomnia-plugin-valorant/src/info-providers/LocalInfoProvider.js:13:27)
    at Object.<anonymous> (/Users/ahlw/Library/Application Support/Insomnia/plugins/insomnia-plugin-valorant/src/info-providers/LocalInfoProvider.js:368:3)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
```

**Comment by techchrism** [comment]
Thanks for the detailed report. This plugin was designed to work only on Windows because it uses the lockfile and local api of Valorant. However, I definitely should add a more descriptive error message and look into making the non-local-Valorant-dependent functionality (token refreshing for example) work cross-platform.
