### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by Moaaz-0x** [techchrism/insomnia-plugin-valorant#6]
Hello I'm getting this error when am trying  to install the plugin

`Error invoking remote method 'installPlugin': Error: Yarn error warning package.json: No license field`

**Comment by techchrism** [comment]
I've been aware of this for a while but unfortunately, I haven't had the time to look into replicating it.
As a workaround, you can open the plugins directory (accessible from the menu) and manually run `npm install insomnia-plugin-valorant`

**Comment by darknblack** [comment]
As an alternative to `npm install insomnia-plugin-valorant`, You can run "git clone insomnia-plugin-valorant" the plugins directory to solve the issue.

**Comment by techchrism** [comment]
Interesting, I wouldn't expect that to work. Insomnia must automatically be installing plugin dependencies or something along those lines.

**Comment by techchrism** [comment]
Good news - I'm able to replicate this issue using yarn.
Bad news - I haven't been able to replicate this within Insomnia.

First, I found the yarn version by running `& "$env:LocalAppData\insomnia\app-2022.7.1\Insomnia.exe" "$env:LocalAppData\insomnia\app-2022.7.1\resources\bin\yarn-standalone.js" -v` (in powershell) with the `ELECTRON_RUN_AS_NODE` environment variable set to `true`.

Then I installed yarn with `npm install -g yarn@1.22.19`
Finally, I got the license warning from running `yarn add insomnia-plugin-valorant --no-lockfile --production` *twice*

**Comment by RiceGrain1** [comment]
Any update to this issue? I'm experiencing the same problem.

**Comment by techchrism** [comment]
I haven't yet found anything that might cause this.
Just to test, can you check if installing other insomnia plugins works as expected?

**Comment by RiceGrain1** [comment]
Nope. I still get the same error trying to install other plugins as well. If I try and manually install it with the code from github I get a different error:
```
Error: Cannot find module 'node-fetch'
Require stack:
- C:\Users\holdi\AppData\Roaming\Insomnia\plugins\insomnia-plugin-valorant-trunk\src\info-providers\RiotAuthProvider.js
- C:\Users\holdi\AppData\Roaming\Insomnia\plugins\insomnia-plugin-valorant-trunk\src\remoteAPI.js
- C:\Users\holdi\AppData\Roaming\Insomnia\plugins\insomnia-plugin-valorant-trunk\plugin.js
- C:\Users\holdi\AppData\Local\insomnia\app-2023.1.0\resources\app.asar\index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3833)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\holdi\AppData\Roaming\Insomnia\plugins\insomnia-plugin-valorant-trunk\src\info-providers\RiotAuthProvider.js:1:174)
    at Object.<anonymous> (C:\Users\holdi\AppData\Roaming\Insomnia\plugins\insomnia-plugin-valorant-trunk\src\info-providers\RiotAuthProvider.js:328:3)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\holdi\AppData\Roaming\Insomnia\plugins\insomnia-plugin-valorant-trunk\src\remoteAPI.js:1:181)
    at Object.<anonymous> (C:\Users\holdi\AppData\Roaming\Insomnia\plugins\insomnia-plugin-valorant-trunk\src\remoteAPI.js:51:3)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\holdi\AppData\Roaming\Insomnia\plugins\insomnia-plugin-valorant-trunk\plugin.js:1:174)
    at Object.<anonymous> (C:\Users\holdi\AppData\Roaming\Insomnia\plugins\insomnia-plugin-valorant-trunk\plugin.js:23:3)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at iU (file:///C:/Users/holdi/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:75164)
    at eI (file:///C:/Users/holdi/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:75814)
    at async f (file:///C:/Users/holdi/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:187:13786)
```

**Comment by techchrism** [comment]
Yeah, if you do a simple git clone, you'd still need to install the dependencies with `npm install`, which is the cause of the most recent error.
Since this happens with other plugins (phew) if you could open an issue at https://github.com/Kong/insomnia/issues and link it here, I'd appreciate it. I did a quick search and at a glance, there doesn't appear to be an existing open issue.

**Comment by RiceGrain1** [comment]
> Yeah, if you do a simple git clone, you'd still need to install the dependencies with `npm install`, which is the cause of the most recent error.
> Since this happens with other plugins (phew) if you could open an issue at https://github.com/Kong/insomnia/issues and link it here, I'd appreciate it. I did a quick search and at a glance, there doesn't appear to be an existing open issue.

Can I just open a ticket there and add a link that links here?

**Comment by techchrism** [comment]
Yeah, that would work too. I'd open it myself but I haven't been successful in replicating it within Insomnia.

**Comment by RiceGrain1** [comment]
So when you try and install the plugin it works for you? Is there a chance we're on different insomnia versions?

**Comment by techchrism** [comment]
Yes, installing the plugin works fine for me, across multiple versions including the latest.

**Comment by RiceGrain1** [comment]
> Yes, installing the plugin works fine for me, across multiple versions including the latest.

Okay well now its halfway working and I literally did not change a thing. I am so confused. When I try and make a request most of them just give me an "Error: Timeout was reached" response. Not sure why it wont go through. 

Would you like me to still make the issue on the insomnia repo?

**Comment by techchrism** [comment]
Yes, if you're still able to replicate the issue (perhaps through uninstalling and reinstalling insomnia), I'd appreciate it if you could open an issue on the insomnia repo.

**Comment by techchrism** [comment]
Replication is trivial - just create a `package.json` in a parent directory (such as the user home directory) with the contents `{}`.

Fixed by my PR here <https://github.com/Kong/insomnia/pull/6829>

I'll close this issue when the fix is merged and released.
